jobs:
  - script: >
        job('SECURITY') {
            scm {
                git {
                    remote {
                        url ('https://github.com/shashwot/jenkins_casc.git')
                        credentials('github-ssh')
                    }
                }
            }

            steps {
                dsl {
                    external('jobdsl/**/*.groovy')
                    removeAction('DELETE')
                }
            }
        }
      
  - script: |
      pipelineJob('prod-go-assignment') {
          definition {
              cpsScm {
                  scm {
                      git {
                        remote { 
                            url ('https://github.com/shashwot/go-assignment.git') 
                            credentials('github-ssh')
                        }
                        branches('main')
                        scriptPath('Jenkinsfile')
                      }
                  }
              }
          }
      }
